### PR TITLE
Change IBAN format for IS (Iceland) (fixes #132)

### LINKED ISSUE #132: Incorrect IBAN format for IS (Iceland)
# Problem

Currently, the library defines the following IBAN format for IS country (Iceland):

4 * bank code + 2 * branch code + 6 * account number + 10 * identification number

However, Wikipedia shows another format: see [International Bank Account Number / IBAN formats by country](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country) page - here is a screenshot
screenshot

where only the first two chars are the bank code, the next two are the branch code, then another two for an account type, and so on.

Even though there are other sources like [xe.com](https://www.xe.com/ibancalculator/iceland/) and [Bank codes](https://bank.codes/iban/structure/iceland/), they seem to be wrong.

Here is an example of why it makes sense to have only 2 letters for the bank code. Let's take IBAN `IS140159260076545510730339` - it belongs to a bank with BIC `NBIIISREXXX`. Searching for this BIC on [ibancalculator.com](https://www.ibancalculator.com/blz.html) gives us a long list of banks where bank codes consist of three digits, and only the leading `1` is common across all these branches, while `59` points to just one of them.

So, if we change the format of the IBAN of Iceland - reduce the bank code from 4 to 2 symbols - we would extract only `01` from the IBAN above, which would result in the same bank code across IBANs pointing to any branch of the bank.

# TODO

Change the IBAN's format for IS code. The new format should be the following:
```
BbanStructureEntry.bankCode(2, 'n'),
BbanStructureEntry.branchCode(2, 'n'),
BbanStructureEntry.accountType(2, 'n'),
BbanStructureEntry.accountNumber(6, 'n'),
BbanStructureEntry.identificationNumber(10, 'n')
```

### PR DESCRIPTION
**Pull request by proshin-roman**
The main change in this pull request is the new IBAN format for IS country code (Iceland). All the rest is more like a code clean up - I hope you don't mind. If these changes are not wanted - I can rollback them.

### CODE REVIEW

**Comment by proshin-roman** [comment]
@arturmkrtchyan could you please take a look at this pull request? Any feedback is welcome!

**Comment by hajk1** [comment]
@proshin-roman I will approve your current PR. For the future please create a separate PR for the formatting and the cleanups.

**Comment by proshin-roman** [comment]
@hajk1 thank you for the approval! You mean two pull requests for the same issue, right? Will do that in the future 👍

**Comment by hajk1** [comment]
@proshin-roman refactoring other parts of the code is a good practice and must be followed on a usual basis. However, mixing the improvements with the other fixes or features makes the review hard.
So it's better to make them separate in terms of better code review and cleaner code history.

**Pull request merged**
